apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-landings-prod
  namespace: argo
spec:
  project: synestra-web
  source:
    repoURL: https://github.com/NeoGrAIph/web-core.git
    targetRevision: main
    path: deploy/charts/web-app
    helm:
      valueFiles:
        - ../../env/release-prod/landings.yaml
        - ../../env/prod/landings.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: web-landings-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
