{{- if and .Values.ingress.enabled .Values.ingress.redirectToHttps -}}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "web-app.fullname" . }}-redirect-https
  labels:
    {{- include "web-app.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ default "2" .Values.argo.syncWaves.app | quote }}
spec:
  redirectScheme:
    scheme: https
    permanent: {{ default true .Values.ingress.redirectPermanent }}
{{- end }}
