# Release values for synestra.io deployment (shared between dev and prod).

image:
  repository: "registry.gitlab.com/synestra/synestra-platform/web-synestra-io"
  tag: "18a4b4b5f65d"
  pullSecrets:
    - name: gitlab-regcred
