apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-payload-dev
  namespace: argo
spec:
  project: synestra-web
  source:
    repoURL: https://github.com/NeoGrAIph/web-core.git
    targetRevision: main
    path: deploy/charts/web-app
    helm:
      valueFiles:
        - ../../env/release-dev/payload-core.yaml
        - ../../env/dev/payload-core.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: web-payload-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: false

