# Release values for payload.services.synestra.tech deployment (prod).

env:
  APP_NAME: "@synestra/payload-core"

image:
  repository: "registry.gitlab.com/synestra/synestra-platform/web-payload-core"
  tag: "2276c2d267a9-r1"
  pullSecrets:
    - name: gitlab-regcred
