# Release values for synestra.io deployment (prod).

env:
  APP_NAME: "@synestra/synestra-io"

image:
  repository: "registry.gitlab.com/synestra/synestra-platform/web-synestra-io"
  tag: "45264c4e095b-r1"
  pullSecrets:
    - name: gitlab-regcred
