# Release values for synestra.io deployment (prod).

env:
  APP_NAME: "@synestra/synestra-io"

image:
  repository: "registry.gitlab.com/synestra/synestra-platform/web-synestra-io"
  tag: "fedd007176c3-r1"
  pullSecrets:
    - name: gitlab-regcred
