# Release values for payload.dev.synestra.tech deployment (dev).

env:
  APP_NAME: "@synestra/payload-core"

image:
  repository: "registry.gitlab.com/synestra/synestra-platform/web-payload-core"
  tag: "bb3d2611ff3b-r1"
  pullSecrets:
    - name: gitlab-regcred

