# Release values for synestra.io deployment (dev).

env:
  APP_NAME: "@synestra/synestra-io"

image:
  repository: "registry.gitlab.com/synestra/synestra-platform/web-synestra-io"
  tag: "66b5a0432b27-r1"
  pullSecrets:
    - name: gitlab-regcred
